name: Tests

on:
  - push
  - pull_request

jobs:
  test-minimal-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pipx install poetry
      - name: Update setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install poetry dependencies
        run: |
          poetry install --with dev || poetry install --with dev || echo "No dev dependency group"
      - name: Setup git
        run: |
          git config --global user.name "CoLRev update"
          git config --global user.email "actions@users.noreply.github.com"
          git config --global url.https://github.com/.insteadOf git://github.com/
      - name: Run poetry tests
        run: poetry run pytest tests/
